version: '2.1'
services:
  code-server:
    image: codercom/code-server:3.12.0
    ports:
      - '8080:8080'
    environment:
      - 'PASSWORD=password'
    volumes:
      - "./project:/home/coder/project"